### ISSUE TITLE
Delaying a payment with flex pay

### ISSUE THREAD

**Issue by martygriffin** [apigy/selfstarter#46]
I cannot for the life of me find how to delay the payment using flexpay. Does the current implementation do this?

**Comment by Jarred-Sumner** [comment]
The current implementation does not have code to charge the multi-use tokens. This is intentional. I don't want to make it easy for scammers, if that problem arises.

I encourage you to read through AmazonFlexPay's documentation on how to charge multi-use tokens. You can find it [here](http://rubydoc.info/gems/amazon_flex_pay/0.9.13/AmazonFlexPay)
