### ISSUE TITLE
User specified / flexible contribution amount

### ISSUE THREAD

**Issue by mark-at-the-undercurrent** [apigy/selfstarter#88]
I do not see any current capability to display a flexible contribution amount form field, rather than radio buttons of pre-defined contribution amounts.

**Comment by Jarred-Sumner** [comment]
Thanks for bringing this up. This is intentional , as people are ordering a product at a risk that it will take a long time to deliver rather than supporting a cause/accepting donations. While you're absolutely welcome to implement this for your own project (this is open-source, after all), this doesn't make sense for Selfstarter proper.—
